unit uTraducaoPT_BR;

interface

uses
  Windows, consts, comconst, dbconsts, comstrs;

type
  TTraducaoPT_BR = class
    private
      class procedure SetResourceString(xOldResourceString: PResStringRec;
                                         xValueChanged: PChar);
    public
      class procedure ChangeValues;
  end;

implementation

{ TTraducaoPT_BR }

class procedure TTraducaoPT_BR.ChangeValues;
begin
  // CONSTS
  SetResourceString(@SOpenFileTitle, 'Abrir');
  SetResourceString(@SCantWriteResourceStreamError, 'Não é possível gravar em uma Stream de recusos somente de leitura');
  SetResourceString(@SDuplicateReference, 'Objeto chamado duas vezes pela mesma instância');
  SetResourceString(@SClassMismatch, 'Recurso %s é de uma classe incorreta');
  SetResourceString(@SInvalidTabIndex, 'Indexador do TAB fora de faixa');
  SetResourceString(@SInvalidTabPosition, 'Posição da aba incompatível com Estilo da aba corrente');
  SetResourceString(@SInvalidTabStyle, 'Estilo da aba incompatível com a posição da aba corrente');
  SetResourceString(@SInvalidBitmap, 'Bitmap inválido');
  SetResourceString(@SInvalidIcon, 'Ícone inválido');
  SetResourceString(@SInvalidMetafile, 'Metafile inválido');
  SetResourceString(@SInvalidPixelFormat, 'Formato de pixel inválido');
  SetResourceString(@SInvalidImage, 'Imagem inválida');
  SetResourceString(@SBitmapEmpty, 'O Bitmap está vazio');
  SetResourceString(@SScanLine, 'Índice da linha de escala está fora da faixa');
  SetResourceString(@SChangeIconSize, 'Não é possível alterar o tamanho do ícone');
  SetResourceString(@SChangeWicSize, 'Não é possível alterar o tamanho de uma imagem WIC');
  SetResourceString(@SOleGraphic, 'Operação inválida no objeto TOleGraphic');
  SetResourceString(@SUnknownExtension, 'Arquivo de imagem com extenção ".%s" desconhecido');
  SetResourceString(@SUnknownClipboardFormat, 'Formato não suportado');
  SetResourceString(@SOutOfResources, 'Sistema sem recursos ou com baixa memória');
  SetResourceString(@SNoCanvasHandle, 'O canvas não esta conseguindo desenhar');
  SetResourceString(@SInvalidTextFormatFlag, 'Formato de texto flag ''%s'' não é suportado');
  SetResourceString(@SInvalidImageSize, 'Tamanho de imagem inválido');
  SetResourceString(@STooManyImages, 'Muitas imagens');
  SetResourceString(@SDimsDoNotMatch, 'Dimensões da imagem diferente da lista de dimensões');
  SetResourceString(@SInvalidImageList, 'ImageList inválido');
  SetResourceString(@SReplaceImage, 'Não é possível trocar a imagem');
  SetResourceString(@SImageIndexError, 'Indexador do ImageList inválido');
  SetResourceString(@SImageReadFail, 'Falha ao ler os dados do ImageList para a stream');
  SetResourceString(@SImageWriteFail, 'Falha ao gravar dados no ImageList para a stream');
  SetResourceString(@SWindowDCError, 'Erro ao criar a janela de contexto do dispositivo');
  SetResourceString(@SClientNotSet, 'Cliente do TDrag não inicializado');
  SetResourceString(@SWindowClass, 'Erro criando a classe da janela');
  SetResourceString(@SWindowCreate, 'Erro criando a janela');
  SetResourceString(@SCannotFocus, 'Não é possível focalizar uma janela desabilitada ou invisível');
  SetResourceString(@SParentRequired, 'Controle "%s" não tem Janela antecessora');
  SetResourceString(@SParentGivenNotAParent, 'Controle requerido não é um ancestral de "%s"');
  SetResourceString(@SMDIChildNotVisible, 'Não é possível esconder um formulário filho MDI');
  SetResourceString(@SVisibleChanged, 'Não é possível trocar a propriedade "Visible" em OnShow ou OnHide');
  SetResourceString(@SCannotShowModal, 'Não é possível marcar uma janela visível como modal');
  SetResourceString(@SScrollBarRange, 'Propriedade Scrollbar está fora de faixa');
  SetResourceString(@SPropertyOutOfRange, 'A propriedade %s está fora de faixa');
  SetResourceString(@SMenuIndexError, 'Índice do menu fora de faixa');
  SetResourceString(@SMenuReinserted, 'Menu inserido duplicadamente');
  SetResourceString(@SMenuNotFound, 'Este sub-menu não está em um menu');
  SetResourceString(@SNoTimers, 'Não há timers disponíveis');
  SetResourceString(@SNotPrinting, 'A Impressora não está imprimindo agora');
  SetResourceString(@SPrinting, 'Impressão em progresso');
  SetResourceString(@SPrinterIndexError, 'Indice de impressoras fora de faixa');
  SetResourceString(@SInvalidPrinter, 'A impressora selecionada não é válida');
  SetResourceString(@SDeviceOnPort, '"%s" em "%s"');
  SetResourceString(@SGroupIndexTooLow, 'GroupIndex não pode ser menor que o ítem de menu anterior ao GroupIndex');
  SetResourceString(@STwoMDIForms, 'Não é possível ter mais de um formulário MDI por aplicação');
  SetResourceString(@SNoMDIForm, 'Não foi possível criar o formulário. Não há formulários MDI ativos neste momento');
  SetResourceString(@SImageCanvasNeedsBitmap, 'Não é possível modificar um TImage que contém um bitmap');
  SetResourceString(@SControlParentSetToSelf, 'Um controle não pode ter ele mesmo como seu antecessor');
  SetResourceString(@SOKButton, 'OK');
  SetResourceString(@SCancelButton, 'Cancelar');
  SetResourceString(@SYesButton, '&Sim');
  SetResourceString(@SNoButton, '&Não');
  SetResourceString(@SHelpButton, '&Ajuda');
  SetResourceString(@SCloseButton, '&Fechar');
  SetResourceString(@SIgnoreButton, '&Ignorar');
  SetResourceString(@SRetryButton, '&Repetir');
  SetResourceString(@SAbortButton, 'Abortar');
  SetResourceString(@SAllButton, '&Todos');
  SetResourceString(@SCannotDragForm, 'Não é possível arrastar um formulário');
  SetResourceString(@SPutObjectError, 'PutObject não definido para ítem');
  SetResourceString(@SCardDLLNotLoaded, 'Não foi possível carregar a biblioteca "CARDS.DLL"');
  SetResourceString(@SDuplicateCardId, 'Encontrada uma duplicata de CardId');
  SetResourceString(@SDdeErr, 'Um erro retornado pelo DDE ($0%x)');
  SetResourceString(@SDdeConvErr, 'Erro no DDE - conversação não estabelecida ($0%x)');
  SetResourceString(@SDdeMemErr, 'Erro ocorrido quando DDE rodou sem memória ($0%x)');
  SetResourceString(@SDdeNoConnect, 'Incapaz de conectar conversação DDE');
  SetResourceString(@SFB, 'FB');
  SetResourceString(@SFG, 'FG');
  SetResourceString(@SBG, 'BG');
  SetResourceString(@SOldTShape, 'Não é possível carregar uma versão antiga de TShape');
  SetResourceString(@SVMetafiles, 'Metafiles');
  SetResourceString(@SVEnhMetafiles, 'Metafiles realçado');
  SetResourceString(@SVIcons, 'Ícone');
  SetResourceString(@SVBitmaps, 'Bitmaps');
  SetResourceString(@SVTIFFImages, 'Imagens TIFF');
  {$IF DEFINED(CLR)}
    SetResourceString(@SVJPGImages, 'Imagens JPEG');
    SetResourceString(@SVPNGImages, 'Imagens PNG');
    SetResourceString(@SVGIFImages, 'Imagens GIF');
  {$ENDIF}
  SetResourceString(@SGridTooLarge, 'Grid muito larga para esta operação');
  SetResourceString(@STooManyDeleted, 'Muitas linhas ou colunas deletadas');
  SetResourceString(@SIndexOutOfRange, 'Índice do grid fora de faixa');
  SetResourceString(@SFixedColTooBig, 'Contador de colunas fixas deve ser menor ou igual que o número de colunas');
  SetResourceString(@SFixedRowTooBig, 'Contador de linhas fixas deve ser menor ou igual ao número de linhas');
  SetResourceString(@SInvalidStringGridOp, 'Não é possível inserir ou deletar linhas da grade');
  SetResourceString(@SInvalidEnumValue, 'Valor Numérico inválido');
  SetResourceString(@SInvalidNumber, 'Valor numérico inválido');
  SetResourceString(@SOutlineIndexError, 'Índice de saída inválido');
  SetResourceString(@SOutlineExpandError, 'O antecessor deve ser expandido');
  SetResourceString(@SInvalidCurrentItem, 'Valor inválido para o ítem corrente');
  SetResourceString(@SMaskErr, 'Valor de entrada inválido');
  SetResourceString(@SMaskEditErr, 'Valor de entrada inválido. Use a tecla Esc para abandonar as alterações');
  SetResourceString(@SOutlineError, 'Índice de saída inválido');
  SetResourceString(@SOutlineBadLevel, 'Nível de transferência incorreto');
  SetResourceString(@SOutlineSelection, 'Seleção inválida');
  SetResourceString(@SOutlineFileLoad, 'Erro ao carregar arquivo');
  SetResourceString(@SOutlineLongLine, 'Linha muito longa');
  SetResourceString(@SOutlineMaxLevels, 'Linha de saída excedeu o limíte máximo');
  SetResourceString(@SMsgDlgWarning, 'Aviso');
  SetResourceString(@SMsgDlgError, 'Erro');
  SetResourceString(@SMsgDlgInformation, 'Informação');
  SetResourceString(@SMsgDlgConfirm, 'Confirmação');
  SetResourceString(@SMsgDlgYes, '&Sim');
  SetResourceString(@SMsgDlgNo, '&Não');
  SetResourceString(@SMsgDlgOK, 'OK');
  SetResourceString(@SMsgDlgCancel, 'Cancela');
  SetResourceString(@SMsgDlgHelp, '&Ajuda');
  SetResourceString(@SMsgDlgHelpNone, 'Ajuda não disponível');
  SetResourceString(@SMsgDlgHelpHelp, 'Ajuda');
  SetResourceString(@SMsgDlgAbort, '&Abortar');
  SetResourceString(@SMsgDlgRetry, '&Repetir');
  SetResourceString(@SMsgDlgIgnore, '&Ignorar');
  SetResourceString(@SMsgDlgAll, '&Todos');
  SetResourceString(@SMsgDlgNoToAll, 'N&ão para todos');
  SetResourceString(@SMsgDlgYesToAll, 'S&im para todos');
  SetResourceString(@SMsgDlgClose, '&Fechar');
  SetResourceString(@SmkcBkSp, 'BkSp');
  SetResourceString(@SmkcTab, 'Tab');
  SetResourceString(@SmkcEsc, 'Esc');
  SetResourceString(@SmkcEnter, 'Enter');
  SetResourceString(@SmkcSpace, 'Space');
  SetResourceString(@SmkcPgUp, 'PgUp');
  SetResourceString(@SmkcPgDn, 'PgDn');
  SetResourceString(@SmkcEnd, 'End');
  SetResourceString(@SmkcHome, 'Home');
  SetResourceString(@SmkcLeft, 'Left');
  SetResourceString(@SmkcUp, 'Up');
  SetResourceString(@SmkcRight, 'Right');
  SetResourceString(@SmkcDown, 'Down');
  SetResourceString(@SmkcIns, 'Ins');
  SetResourceString(@SmkcDel, 'Del');
  SetResourceString(@SmkcShift, 'Shift+');
  SetResourceString(@SmkcCtrl, 'Ctrl+');
  SetResourceString(@SmkcAlt, 'Alt+');
  SetResourceString(@srUnknown, '(Ignorado)');
  SetResourceString(@srNone, '(Nenhum)');
  SetResourceString(@SOutOfRange, 'Valor deve estar entre %d e %d');
  SetResourceString(@SDateEncodeError, 'Arqumento inválido para decodificar data');
  SetResourceString(@SDefaultFilter, 'Todos os arquivos (*.*)|*.*');
  SetResourceString(@sAllFilter, 'Todos');
  SetResourceString(@SNoVolumeLabel, ': [ - sem rótulo - ]');
  SetResourceString(@SInsertLineError, 'Não é possível inserir linhas');
  SetResourceString(@SConfirmCreateDir, 'O diretório especificado não existe. Criá-lo?');
  SetResourceString(@SSelectDirCap, 'Selecione o diretório');
  SetResourceString(@SDirNameCap, 'Diretório &Nome:');
  SetResourceString(@SDrivesCap, 'D&rives:');
  SetResourceString(@SDirsCap, '&Diretorios:');
  SetResourceString(@SFilesCap, '&Arquivos: (*.*)');
  SetResourceString(@SNetworkCap, 'R&ede...');
  SetResourceString(@SInvalidClipFmt, 'Formato na área de transferência inválido');
  SetResourceString(@SIconToClipboard, 'Área de transferência não suporta ícones');
  SetResourceString(@SCannotOpenClipboard, 'Não posso abrir a área de transferência');
  SetResourceString(@SDefault, 'Padrão');
  SetResourceString(@SInvalidMemoSize, 'Texto excedeu a capacidade de 32K');
  SetResourceString(@SCustomColors, 'Personalizar Cores');
  SetResourceString(@SInvalidPrinterOp, 'Operação não suportada ao selecionar impressora');
  SetResourceString(@SNoDefaultPrinter, 'Esta impressora selecionada não é a default');
  SetResourceString(@SIniFileWriteError, 'Incapaz de gravar para "%s"');
  SetResourceString(@SBitsIndexError, 'Índice de Bits fora de faixa');
  SetResourceString(@SUntitled, '(Sem Título)');
  SetResourceString(@SInvalidRegType, 'Tipo de dado inválido para "%s"');
  SetResourceString(@SUnknownConversion, 'Incapaz de converter arquivo de extenção (.%s) para RichEdit');
  SetResourceString(@SDuplicateMenus, 'Menu "%s" já está inicializado e usado por outro formulário');
  SetResourceString(@SPictureLabel, 'Imagem:');
  SetResourceString(@SPictureDesc, ' (%dx%d)');
  SetResourceString(@SPreviewLabel, 'Visualizar');
  SetResourceString(@SCannotOpenAVI, 'Não é possível abrir arquivo AVI');
  SetResourceString(@SNotOpenErr, 'Dispositivo MCI não aberto');
  SetResourceString(@SMPOpenFilter, 'Todos arquivos (*.*)|*.*|Arquivos wave (*.wav)|*.wav|Arquivos Midi (*.mid)|*.mid|Vídeo para Windows (*.avi)|*.avi');
  SetResourceString(@SMCINil, '');
  SetResourceString(@SMCIAVIVideo, 'AVIVídeo');
  SetResourceString(@SMCICDAudio, 'CDAudio');
  SetResourceString(@SMCIDAT, 'DAT');
  SetResourceString(@SMCIDigitalVideo, 'Vídeo Digital');
  SetResourceString(@SMCIMMMovie, 'MMMovie');
  SetResourceString(@SMCIOther, 'Outro');
  SetResourceString(@SMCIOverlay, 'Sobreposto');
  SetResourceString(@SMCIScanner, 'Scanner');
  SetResourceString(@SMCISequencer, 'Seqüência');
  SetResourceString(@SMCIVCR, 'VCR');
  SetResourceString(@SMCIVideodisc, 'Vídeo disco');
  SetResourceString(@SMCIWaveAudio, 'Áudio Wave');
  SetResourceString(@SMCIUnknownError, 'Código de erro desconhecido');
  SetResourceString(@SBoldItalicFont, 'Negrito Itálico');
  SetResourceString(@SBoldFont, 'Negrito');
  SetResourceString(@SItalicFont, 'Itálico');
  SetResourceString(@SRegularFont, 'Normal');
  SetResourceString(@SPropertiesVerb, 'Propriedades');
  SetResourceString(@SServiceFailed, 'Falha de serviço em %s: %s');
  SetResourceString(@SExecute, 'Executar');
  SetResourceString(@SStart, 'Iniciar');
  SetResourceString(@SStop, 'Parar');
  SetResourceString(@SPause, 'pausa');
  SetResourceString(@SContinue, 'continuar');
  SetResourceString(@SInterrogate, 'interrogar');
  SetResourceString(@SShutdown, 'Reiniciar');
  SetResourceString(@SCustomError, 'Falha de serviço sob a mensagem (%d): %s');
  SetResourceString(@SServiceInstallOK, 'Serviço instalado com sucesso');
  SetResourceString(@SServiceInstallFailed, 'Serviço "%s" falhou ou foi instalado com erro: "%s"');
  SetResourceString(@SServiceUninstallOK, 'Serviço desinstalado com successo');
  SetResourceString(@SServiceUninstallFailed, 'Serviço "%s" falhou ou foi desinstalado com erro: "%s"');
  SetResourceString(@SDockedCtlNeedsName, 'O controle acoplado deve ter um conhecido');
  SetResourceString(@SDockTreeRemoveError, 'Erro removendo controle da árvore');
  SetResourceString(@SDockZoneNotFound, ' - Zona da doca não encontrada');
  SetResourceString(@SDockZoneHasNoCtl, ' - Zona da doca não tem controle');
  SetResourceString(@SDockZoneVersionConflict, 'Erro ao carregar zona da doca da stream. ' +  'Versão esperada %d, versão encontrada %d.');
  SetResourceString(@SAllCommands, 'Todos Comandos');
  SetResourceString(@SDuplicateItem, 'Lista não permite duplicados ($0%x)');
  SetResourceString(@STextNotFound, 'Texto não encontrado: "%s"');
  SetResourceString(@SBrowserExecError, 'Nenhum navegador padrão é especificado');
  SetResourceString(@SColorBoxCustomCaption, 'Customizar...');
  SetResourceString(@SMultiSelectRequired, 'Modo multiseleção deve permanecer ativo para esse recurso');
  SetResourceString(@SPromptArrayTooShort, 'O comprimento do  Length of value array must be >= length of prompt array');
  SetResourceString(@SPromptArrayEmpty, 'Prompt array must not be empty');
  SetResourceString(@SUsername, '&Usuário');
  SetResourceString(@SPassword, '&Senha');
  SetResourceString(@SDomain, '&Domínio');
  SetResourceString(@SLogin, 'Login');
  SetResourceString(@SKeyCaption, 'Chave');
  SetResourceString(@SValueCaption, 'Valor');
  SetResourceString(@SKeyConflict, 'Uma chave com o nome de "%s" já existe');
  SetResourceString(@SKeyNotFound, 'Chave "%s" não encontrada');
  SetResourceString(@SNoColumnMoving, 'goColMoving não é uma opção suportada');
  SetResourceString(@SNoEqualsInKey, 'Chave não pode conter sinal igual a ("=")');
  SetResourceString(@SSendError, 'Erro enviando email');
  SetResourceString(@SAssignSubItemError, 'Não é possível associar um subítem de uma actionbar quanto um de seus antecessores estiver associado ao actionbar');
  SetResourceString(@SDeleteItemWithSubItems, 'O item "%s" possui subitens, apagar mesmo assim?');
  SetResourceString(@SDeleteNotAllowed, 'Não é permitido apagar este item');
  SetResourceString(@SMoveNotAllowed, 'Item "%s" não tem permissão de ser movido');
  SetResourceString(@SMoreButtons, 'Mais Botões');
  SetResourceString(@SErrorDownloadingURL, 'Erro carregando URL: "%s"');
  SetResourceString(@SUrlMonDllMissing, 'Impossível carregar "%s"');
  SetResourceString(@SAllActions, '(Todas as Ações)');
  SetResourceString(@SNoCategory, '(Sem Categoria)');
  SetResourceString(@SExpand, 'Expandir');
  SetResourceString(@SErrorSettingPath, 'Erro ajustando path: "%s"');
  SetResourceString(@SLBPutError, 'Erro tentando inserir ítens em um listbox de estilo virtual');
  SetResourceString(@SErrorLoadingFile, 'Erro carregando arquivo de ajustes salvos anteriormente: "%s"'#13'Você gostaria de apagá-lo?');
  SetResourceString(@SResetUsageData, 'Restaurar todos os dados usados?');
  SetResourceString(@SFileRunDialogTitle, 'Executar');
  SetResourceString(@SNoName, '(Sem Nome Name)');
  SetResourceString(@SErrorActionManagerNotAssigned, 'ActionManager deve primeiro ser atribuído');
  SetResourceString(@SAddRemoveButtons, '&Adiciona ou Remove Botões');
  SetResourceString(@SResetActionToolBar, 'Restaurar Toolbar');
  SetResourceString(@SCustomize, '&Customizar');
  SetResourceString(@SSeparator, 'Separador');
  SetResourceString(@SCannotHideActionBand, '"%s" não pode ser ocultada');
  SetResourceString(@SErrorSettingCount, 'Erro ajustando %s.Count');
  SetResourceString(@SListBoxMustBeVirtual, 'O Estilo do Listbox (%s) deve ser virtual na ordem para ajustar o Countador');
  SetResourceString(@SUnableToSaveSettings, 'Não foi possível salvar as alterações');
  SetResourceString(@SRestoreDefaultSchedule, 'Você gostaria de restaurar para a Programação Prioritária padrão?');
  SetResourceString(@SNoGetItemEventHandler, 'Nemhum manipulador de evento OnGetItem atribuído');
  SetResourceString(@SInvalidColorMap, 'ActionBand com mapa de cores inválido. Ele requer mapa de cores do tipo TCustomActionBarColorMapEx');
  SetResourceString(@SDuplicateActionBarStyleName, 'Um estilo chamado "%s" já foi registrado');
  SetResourceString(@SStandardStyleActionBars, 'Estilo Standard');
  SetResourceString(@SXPStyleActionBars, 'Estilo XP');
  SetResourceString(@SActionBarStyleMissing, 'Unit sem nenhum estilo ActionBand presente na cláusula uses.'#13 +'Sua aplicação deve incluir qualquer XPStyleActnCtrls, StdStyleActnCtrls ou '+'um componente ActionBand de terceiros presente na cláusula uses.');
  SetResourceString(@sParameterCannotBeNil,  '%s parâmetro na chamada para %s não pode ser nulo');
  SetResourceString(@SInvalidColorString, 'String de cor inválida');
  SetResourceString(@SActionManagerNotAssigned, 'A propriedade %s do gerenciador de ações não foi atribuído');
  SetResourceString(@SInvalidPath, '"%s" é um caminho inválido');
  SetResourceString(@SInvalidPathCaption, 'Caminho inválido');
  SetResourceString(@SANSIEncoding, 'ANSI');
  SetResourceString(@SASCIIEncoding, 'ASCII');
  SetResourceString(@SUnicodeEncoding, 'Unicode');
  SetResourceString(@SBigEndianEncoding, 'Big Endian Unicode');
  SetResourceString(@SUTF8Encoding, 'UTF-8');
  SetResourceString(@SUTF7Encoding, 'UTF-7');
  SetResourceString(@SEncodingLabel, 'Encoding:');
  SetResourceString(@sCannotAddFixedSize, 'Não é possível adicionar colunas ou linhas enquanto o estilo expandido tem tamanho fixo.');
  SetResourceString(@sInvalidSpan, '''%d'' não é um alcance válido');
  SetResourceString(@sInvalidRowIndex, 'Índice da linha, %d, fora dos limites');
  SetResourceString(@sInvalidColumnIndex, 'Índice da coluna, %d, fora dos limites');
  SetResourceString(@sInvalidControlItem, 'ControlItem.Control não pode ser atribuído para possuír um GridPanel');
  SetResourceString(@sCannotDeleteColumn, 'Não é possível excluir uma coluna que contêm controles');
  SetResourceString(@sCannotDeleteRow, 'Não é possível excluir uma linha que contêm controles');
  SetResourceString(@sCellMember, 'Membro');
  SetResourceString(@sCellSizeType, 'Tipo do tamanho');
  SetResourceString(@sCellValue, 'Valor');
  SetResourceString(@sCellAutoSize, 'Auto');
  SetResourceString(@sCellPercentSize, 'Percentual');
  SetResourceString(@sCellAbsoluteSize, 'Absoluto');
  SetResourceString(@sCellColumn, 'Coluna%d');
  SetResourceString(@sCellRow, 'Linha%d');
  SetResourceString(@STrayIconRemoveError, 'Não é possível remover o ícone das notificações concha(shell)');
  SetResourceString(@STrayIconCreateError, 'Não é possível criar ícone de notificação concha(shell)');
  SetResourceString(@SPageControlNotSet, 'PageControl deve primeiro ser atribuído');
  SetResourceString(@SWindowsVistaRequired, '%s requer Windows Vista ou superior');
  SetResourceString(@SXPThemesRequired, '%s requer temas para ser habilitado');
  SetResourceString(@STaskDlgButtonCaption, 'Button%d');
  SetResourceString(@STaskDlgRadioButtonCaption, 'RadioButton%d');
  SetResourceString(@SInvalidTaskDlgButtonCaption, 'Caption não pode ser vazio');
  SetResourceString(@SInvalidCategoryPanelParent, 'CategoryPanel deve conter um CategoryPanelGroup como seu pai');
  SetResourceString(@SInvalidCategoryPanelGroupChild, 'Apenas CategoryPanels podem ser inseridos em um CategoryPanelGroup');
  SetResourceString(@SInvalidCanvasOperation, 'Operação com canvas inválida');
  SetResourceString(@SNoOwner, '%s não tem dono');
  SetResourceString(@SRequireSameOwner, 'Origem e destino requer o mesmo dono');
  SetResourceString(@SDirect2DInvalidOwner, '%s não pode ser adquirido por um canvas diferente');
  SetResourceString(@SDirect2DInvalidSolidBrush, 'pincel de cor inválida');
  SetResourceString(@SDirect2DInvalidBrushStyle, 'pincel de estilo inválido');
  SetResourceString(@SKeyboardLocaleInfo, 'Erro ao recuperar informações locais');
  SetResourceString(@SKeyboardLangChange, 'Falha ao modificar o idioma de entrada');
  SetResourceString(@SOnlyWinControls, 'Você pode anexar somente abas TWinControl baseadas em Controls');
  SetResourceString(@SNoKeyword, 'Nenhuma palavra chave especificada');
  SetResourceString(@SStyleLoadError, 'Não é possível carregar o estilo ''$s''');
  SetResourceString(@SStyleLoadErrors, 'Não é possível carregar os estilos: %s');
  SetResourceString(@SStyleRegisterError, 'O estilo ''%s'' já está registrado');
  SetResourceString(@SStyleClassRegisterError, 'Classe de estilo ''%s'' já está registrada');
  SetResourceString(@SStyleNotFound, 'Estilo ''%s'' não encontrado');
  SetResourceString(@SStyleClassNotFound, 'Classe de estilo ''%s'' não encontrada');
  SetResourceString(@SStyleInvalidHandle, 'Controlador de estilo inválido');
  SetResourceString(@SStyleFormatError, 'Formato de estilo inválido');
  SetResourceString(@SStyleFileDescription, 'Arquivo de estilo VCL');
  SetResourceString(@SStyleHookClassRegistered, 'Classe ''%s'' já está registrada para ''%s''');
  SetResourceString(@SStyleHookClassNotRegistered, 'Classe ''%s'' não está registrada para ''%s''');
  SetResourceString(@SStyleInvalidParameter, '%s parâmetro não pode ser nulo');
  SetResourceString(@SStyleHookClassNotFound, 'Uma classe StyleHook não pode ser registrada para %s');
  SetResourceString(@SStyleFeatureNotSupported, 'Recurso não suportado por esse estilo');
  SetResourceString(@SStyleNotRegistered, 'Estilo ''%s'' não está registrado');
  SetResourceString(@SStyleUnregisterError, 'Não é possível cancelar o registro do sistema de estilo');
  SetResourceString(@SStyleNotRegisteredNoName, 'Estilo não registrado');
  SetResourceString(@SNameBlack, 'Preto');
  SetResourceString(@SNameMaroon, 'Marrom');
  SetResourceString(@SNameGreen, 'Verde');
  SetResourceString(@SNameOlive, 'Oliva');
  SetResourceString(@SNameNavy, 'Marinho');
  SetResourceString(@SNamePurple, 'Roxo');
  SetResourceString(@SNameTeal, 'Cerceta');
  SetResourceString(@SNameGray, 'Cinza');
  SetResourceString(@SNameSilver, 'Prata');
  SetResourceString(@SNameRed, 'Vermelho');
  SetResourceString(@SNameLime, 'Limão');
  SetResourceString(@SNameYellow, 'Amarelo');
  SetResourceString(@SNameBlue, 'Azul');
  SetResourceString(@SNameFuchsia, 'Fuchsia');
  SetResourceString(@SNameAqua, 'Agua');
  SetResourceString(@SNameWhite, 'Branco');
  SetResourceString(@SNameMoneyGreen, 'Verde dinheiro');
  SetResourceString(@SNameSkyBlue, 'Azul céu');
  SetResourceString(@SNameCream, 'Creme');
  SetResourceString(@SNameMedGray, 'Cinza médio');
  SetResourceString(@SNameActiveBorder, 'Borda ativa');
  SetResourceString(@SNameActiveCaption, 'Caption Ativo');
  SetResourceString(@SNameAppWorkSpace, 'Aplicativo de área de trabalho');
  SetResourceString(@SNameBackground, 'Plano de fundo');
  SetResourceString(@SNameBtnFace, 'Cara do botão');
  SetResourceString(@SNameBtnHighlight, 'Realce do botão');
  SetResourceString(@SNameBtnShadow, 'Sombra do botão');
  SetResourceString(@SNameBtnText, 'Texto to botão');
  SetResourceString(@SNameCaptionText, 'Texto Caption');
  SetResourceString(@SNameDefault, 'Padrão');
  SetResourceString(@SNameGradientActiveCaption, 'Gradiente ativo Caption');
  SetResourceString(@SNameGradientInactiveCaption, 'Gradiente inativo Caption');
  SetResourceString(@SNameGrayText, 'Texto cinzento');
  SetResourceString(@SNameHighlight, 'Realce do plano de fundo');
  SetResourceString(@SNameHighlightText, 'Texto em realce');
  SetResourceString(@SNameHotLight, 'Luz quente');
  SetResourceString(@SNameInactiveBorder, 'Borda inativa');
  SetResourceString(@SNameInactiveCaption, 'Caption inativo');
  SetResourceString(@SNameInactiveCaptionText, 'Texto de caption inativo');
  SetResourceString(@SNameInfoBk, 'Informações de plano de fundo');
  SetResourceString(@SNameInfoText, 'Texto informativo');
  SetResourceString(@SNameMenu, 'Plano de fundo do menu');
  SetResourceString(@SNameMenuBar, 'Barra de menu');
  SetResourceString(@SNameMenuHighlight, 'Realce do menu');
  SetResourceString(@SNameMenuText, 'Texto do menu');
  SetResourceString(@SNameNone, 'Nenhum');
  SetResourceString(@SNameScrollBar, 'Barra de rolagem');
  SetResourceString(@SName3DDkShadow, 'Sombra escura 3D');
  SetResourceString(@SName3DLight, 'Iluminação 3D');
  SetResourceString(@SNameWindow, 'Plano de fundo de janela');
  SetResourceString(@SNameWindowFrame, 'Estrutura de janela');
  SetResourceString(@SNameWindowText, 'Texto de janela');
  SetResourceString(@SInvalidBitmapPixelFormat, 'Formato de pixel bitmap inválido, pode ser uma imagem de 32 bits');
  SetResourceString(@SJumplistsItemErrorGetpsi, 'Consultando a interface IPropertyStore');
  SetResourceString(@SJumplistsItemErrorInitializepropvar, 'Inicializando uma propriedade variável');
  SetResourceString(@SJumplistsItemErrorSetps, 'Configurando o valor de armazenamento de propriedades');
  SetResourceString(@SJumplistsItemErrorCommitps, 'Cometendo o armazenamento de propriedade');
  SetResourceString(@SJumplistsItemErrorSettingarguments, 'Configurando os argumentos de uma lista de salto de itens');
  SetResourceString(@SJumplistsItemErrorSettingpath, 'Configurando o caminho de uma lista de salto de itens');
  SetResourceString(@SJumplistsItemErrorSettingicon, 'Configurando a localização de um ícone de uma lista de salto de itens');
  SetResourceString(@SJumplistsItemErrorAddingtobjarr, 'Inserindo um item a um array de objetos');
  SetResourceString(@SJumplistsItemErrorGettingobjarr, 'Consultando a interface de IObjectArray');
  SetResourceString(@SJumplistsItemErrorNofriendlyname, 'A propriedade FriendlyName de um item não pode ser vazio');
  SetResourceString(@SJumplistsItemException, 'Exceção JumpListItem: Erro %d: %s');
  SetResourceString(@SJumplistException, 'Exceção JumpList: Erro %d: %s');
  SetResourceString(@SJumplistErrorBeginlist, 'Iniciando uma sessão de construção para uma nova lista de salto');
  SetResourceString(@SJumplistErrorAppendrc, 'Acrescentando um item para a categoria de arquivos de lista de uma nova lista de salto');
  SetResourceString(@SJumplistErrorAppendfc, 'Acrescentando um item para a categoria de arquivos frequentes de uma nova lista de salto');
  SetResourceString(@SJumplistErrorAddusertasks, 'Inserindo suas tarefas para uma nova lista de salto');
  SetResourceString(@SJumplistErrorAddcategory, 'Inserindo uma categoria personalizada (''%s'') e seus itens herdados para uma nova lista de salto');
  SetResourceString(@SJumplistErrorCommitlist, 'Cometendo uma nova lista de salto');
  SetResourceString(@SJumplistExceptionInvalidOS, 'O sistema operacional atual não suporta listas de salto');
  SetResourceString(@SJumplistExceptionAppID, 'O processo atual já contem um identificador de aplicação: %s');
  SetResourceString(@sBeginInvokeNoHandle, 'Não é possível chamar BeginInvoke em um controlador sem pai ou controlador de janela');
  SetResourceString(@SToggleSwitchCaptionOn, 'On');
  SetResourceString(@SToggleSwitchCaptionOff, 'Off');
  SetResourceString(@SInvalidRelativePanelControlItem, 'ControlItem.Control não pode ser atribuído para possuír um RelativePanel');
  SetResourceString(@SInvalidRelativePanelSibling, 'Controlador não é um irmão sem RelativePanel');
  SetResourceString(@SInvalidRelativePanelSiblingSelf, 'Controlador não pode ser posicionado em relação a ele mesmo');

  // DBCONSTS ==================================================================
  SetResourceString(@SInvalidFieldSize , 'Tamanho de campo inválido');
  SetResourceString(@SInvalidFieldKind , 'FieldKind inválido');
  SetResourceString(@SInvalidFieldRegistration , 'Registro de campo inválido');
  SetResourceString(@SUnknownFieldType , 'Campo "%s" de tipo desconhecido');
  SetResourceString(@SFieldNameMissing , 'Nome do campo ausente');
  SetResourceString(@SDuplicateFieldName , 'Nome de campo duplicado "%s"');
  SetResourceString(@SFieldNotFound , '%s: Campo "%s" não encontrado');
  SetResourceString(@SFieldAccessError , 'Não é possível acessar o campo "%s" do tipo %s');
  SetResourceString(@SFieldValueError , 'Valor inválido para o campo "%s"');
  SetResourceString(@SFieldRangeError , '%g Não é um valor válido para o campo "%s". A faixa permitida é de %g até %g');
  SetResourceString(@SBcdFieldRangeError , '%s não é um valor válido para o campo "%s". A faixa permitida vai de %s até %s');
  SetResourceString(@SInvalidIntegerValue , '"%s" não é um inteiro válido para o campo "%s"');
  SetResourceString(@SInvalidBoolValue , '"%s" não é uma valor boleano válido para o campo "%s"');
  SetResourceString(@SInvalidFloatValue , '"%s" não é um valor de ponto flutuante válido para o campo "%s"');
  SetResourceString(@SFieldTypeMismatch , 'Campo "%s" não é do tipo esperado');
  SetResourceString(@SFieldSizeMismatch , 'Tamanho sem combinação para campo "%s", esperando: %d atual: %d');
  SetResourceString(@SInvalidVarByteArray , 'Tipo ou tamanho da variante inválido para o campo "%s"');
  SetResourceString(@SFieldOutOfRange , 'Valor do campo "%s" está fora de faixa');
  SetResourceString(@SCantAdjustPrecision , 'Erro de ajuste de precisão BCD');
  SetResourceString(@SFieldRequired , 'Campo "%s" é requerido e deve ter um valor');
  SetResourceString(@SDataSetMissing , 'Dataset "%s" desconhecido ou não encontrado');
  SetResourceString(@SInvalidCalcType , 'Campo "%s" não pode ser um campo calculado ou lookup');
  SetResourceString(@SFieldReadOnly , 'Campo "%s" não pode ser modificado. Ele está em modo somente-leitura');
  SetResourceString(@SFieldIndexError , 'Índice de campo fora de faixa');
  SetResourceString(@SNoFieldIndexes , 'Índice corrente não ativo');
  SetResourceString(@SNotIndexField , 'Campo "%s" não está indexado e não pode ser modificado');
  SetResourceString(@SIndexFieldMissing , 'Não é possível acessar o índice do campo "%s"');
  SetResourceString(@SDuplicateIndexName , 'Nome de índice duplicado "%s"');
  SetResourceString(@SNoIndexForFields , '"%s" não tem índice para os campos "%s"');
  SetResourceString(@SIndexNotFound , 'Índice "%s" não encontrado');
  SetResourceString(@SDBDuplicateName , 'Nome duplicado "%s" em "%s"');
  SetResourceString(@SCircularDataLink , 'Ligações de dados circulares não são permitidas');
  SetResourceString(@SLookupInfoError , 'Informação Lookup para o campo "%s" está incompleta');
  SetResourceString(@SNewLookupFieldCaption , 'Novo Campo Lookup');
  SetResourceString(@SDataSourceChange , 'Este DataSource não pode ser atualizado');
  SetResourceString(@SNoNestedMasterSource , 'Arquivos aninhados não podem ter uma tabela mestra');
  SetResourceString(@SDataSetOpen , 'Não é possível realizar esta operação em um Dataset');
  SetResourceString(@SNotEditing , 'O Dataset não está em modo de edição ou inserção');
  SetResourceString(@SDataSetClosed , 'Não é possível realizar esta operação em um Dataset fechado');
  SetResourceString(@SDataSetEmpty , 'Não é possível realizar esta operação em um Dataset vazio');
  SetResourceString(@SDataSetReadOnly , 'Não é possível modificar um Dataset somente de leitura');
  SetResourceString(@SNestedDataSetClass , 'Dataset aninhado têm que herdar de "%s"');
  SetResourceString(@SExprTermination , 'Expressão de filtro incorretamente terminada');
  SetResourceString(@SExprNameError , 'Nome de campo não terminado');
  SetResourceString(@SExprStringError , 'Constante de string não terminada');
  SetResourceString(@SExprInvalidChar , 'Caractere inválido na expressão de filtro: "%s"');
  SetResourceString(@SExprNoLParen , '"(" esperado mas "%s" encontrado');
  SetResourceString(@SExprNoRParen , '")" esperado mas "%s" encontrado');
  SetResourceString(@SExprNoRParenOrComma , '")" ou "," aguardado mas "%s" existe');
  SetResourceString(@SExprExpected , 'Expressão esperada mas "%s" encontrada');
  SetResourceString(@SExprBadField , 'Campo "%s" não pode ser usado em uma expressão de filtro');
  SetResourceString(@SExprBadNullTest , 'NULL somente permitido com "=" e "<>"');
  SetResourceString(@SExprRangeError , 'Constante fora de faixa');
  SetResourceString(@SExprNotBoolean , 'Campo "%s" não é do tipo boleano');
  SetResourceString(@SExprIncorrect , 'Expressão de filtro formada incorretamente');
  SetResourceString(@SExprNothing , 'Absolutamente');
  SetResourceString(@SExprTypeMis , 'Tipo de expressão desconhecida');
  SetResourceString(@SExprBadScope , 'Operação não pode misturar valor agregado com valor registro-variado');
  SetResourceString(@SExprNoArith , 'Filtro de expressão aritmética não suportada');
  SetResourceString(@SExprNotAgg , 'Expressão não é uma expressão agregada');
  SetResourceString(@SExprBadConst , 'Constante corrente não é do tipo "%s"');
  SetResourceString(@SExprNoAggFilter , 'Expressões agregadas não permitem filtros');
  SetResourceString(@SExprEmptyInList , 'Lista de predicados IN pode não estar vazia');
  SetResourceString(@SInvalidKeywordUse , 'Uso de Keyword inválido');
  SetResourceString(@STextFalse , 'Falso');
  SetResourceString(@STextTrue , 'Verdadeiro');
  SetResourceString(@SParameterNotFound , 'Parametro "%s" não encontrado');
  SetResourceString(@SInvalidVersion , 'Não é possível carregar parâmetros da fita');
  SetResourceString(@SParamTooBig , 'Parâmetro "%s", não é possível salvar dados maiores que "%d" bytes');
  SetResourceString(@SBadFieldType , 'Campo "%s" é um tipo não suportado');
  SetResourceString(@SAggActive , 'Esta propriedade não pode ser modificada enquanto o agregado está ativo');
  SetResourceString(@SProviderSQLNotSupported , 'Sentença SQL não suportada: "%s"');
  SetResourceString(@SProviderExecuteNotSupported , 'Execução não suportada: "%s"');
  SetResourceString(@SExprNoAggOnCalcs , 'Campo "%s" não é do tipo campo calculado para ser usado em uma agregação. use um calculo interno');
  SetResourceString(@SRecordChanged , 'Registro foi alterado por outro usuário');
  SetResourceString(@SDataSetUnidirectional , 'Operação não permitida em um dataset unidirecional');
  SetResourceString(@SUnassignedVar , 'Valor variant não atribuído');
  SetResourceString(@SRecordNotFound , 'Registro não encontrado');
  SetResourceString(@SFileNameBlank , 'Propriedade FileName não pode ser vazia');
  SetResourceString(@SFieldNameTooLarge , 'Nome de campo "%s" excede %d caracteres');
  SetResourceString(@SBcdOverflow , 'BCD estouro de capacidade');
  SetResourceString(@SInvalidBcdValue , '"%s" não é uma valor BCD válido');
  SetResourceString(@SInvalidFormatType , 'Tipo de formato inválido para BCD');
  SetResourceString(@SCouldNotParseTimeStamp , 'Poderia não analisar string SQL TimeStamp');
  SetResourceString(@SInvalidSqlTimeStamp , 'Valores de SQL data/hota inválidas');
  SetResourceString(@SCalendarTimeCannotBeRepresented , 'Tempo do calendário não pode ser representado');
  SetResourceString(@SDeleteRecordQuestion , 'Apagar registro?');
  SetResourceString(@SDeleteMultipleRecordsQuestion , 'Apagar todos os registros selecionados?');
  SetResourceString(@STooManyColumns , 'Grid requisitou para mostrar mais do que 256 colunas');
  SetResourceString(@SSkip , 'Skip');
  SetResourceString(@SAbort , 'Abortar');
  SetResourceString(@SMerge , 'Mesclar');
  SetResourceString(@SCorrect , 'Corrigir');
  SetResourceString(@SCancel  , 'Cancelar');
  SetResourceString(@SRefresh , 'Atualizar');
  SetResourceString(@SModified , 'Modificado');
  SetResourceString(@SInserted , 'Inserido');
  SetResourceString(@SDeleted  , 'Apagado');
  SetResourceString(@SCaption , 'Erro de atualização - %s');
  SetResourceString(@SUnchanged , '<Não alterado>');
  SetResourceString(@SBinary , '(Binário)');
  SetResourceString(@SAdt , '(ADT)');
  SetResourceString(@SArray , '(Matriz)');
  SetResourceString(@SFieldName , 'Nome do Campo');
  SetResourceString(@SOriginal , 'Valor Original');
  SetResourceString(@SConflict , 'Valor Conflitante');
  SetResourceString(@SValue , ' Valor');
  SetResourceString(@SNoData , '<Sem Registros>');
  SetResourceString(@SNew , 'Novo');

  // COMSTRS ===================================================================
  SetResourceString(@sTabFailClear , 'Falha ao limpar controle de aba');
  SetResourceString(@sTabFailDelete , 'Falha ao deletar índice "%d" da aba');
  SetResourceString(@sTabFailRetrieve , 'Falha ao recuperar a aba no índice "%d"');
  SetResourceString(@sTabFailGetObject , 'Falha ao inicializar objeto no índice "%d"');
  SetResourceString(@sTabFailSet , 'Falha ao ajustar a aba "%s" no índice "%d"');
  SetResourceString(@sTabFailSetObject , 'Falha ao ajustar o objeto no índice "%d"');
  SetResourceString(@sTabMustBeMultiLine , 'O MultiLine deve ser verdadeiro quando TabPosition for tpLeft ou tpRight ');
  SetResourceString(@sInvalidLevel , 'Nível de ítem atribuído inválido');
  SetResourceString(@sInvalidLevelEx , 'Nível inválido (%d) para o item "%s"');
  SetResourceString(@sInvalidIndex , 'Índice inválido');
  SetResourceString(@sInsertError , 'Erro de inserção');
  SetResourceString(@sInvalidOwner , 'Proprietário Inválido');
  SetResourceString(@sUnableToCreateColumn , 'Não é possível criar uma nova coluna');
  SetResourceString(@sUnableToCreateItem , 'Não é possível criar um novo item');
  SetResourceString(@sRichEditInsertError , 'Erro inserindo linha no RichEdit');
  SetResourceString(@sRichEditLoadFail , 'Falha ao tentar carregar Stream');
  SetResourceString(@sRichEditSaveFail , 'Falha ao tentar salvar Stream');
  SetResourceString(@sTooManyPanels , 'Barra de status não pode ter mais de 64 painéis');
  SetResourceString(@sHKError , 'Erro ao atribuir Hot-Key à "%s". "%s"');
  SetResourceString(@sHKInvalid , 'Hot-Key inválida');
  SetResourceString(@sHKInvalidWindow , 'A janela é inválida ou é uma Janela filha');
  SetResourceString(@sHKAssigned , 'Esta Hot-Key está atribuída a uma outra janela');
  SetResourceString(@sUDAssociated , '"%s" já é associado para "%s"');
  SetResourceString(@sPageIndexError , '"%d" é um valor de índice de página inválido. O índice de página deve estar entre 0 e %d');
  SetResourceString(@sInvalidComCtl32 , 'Este controle requer COMCTL32.DLL versão 4.70 ou superior');
  SetResourceString(@sDateTimeMax , 'A data excede o valor máximo de "%s"');
  SetResourceString(@sDateTimeMin , 'A data é menor que o valor mínimo de "%s"');
  SetResourceString(@sNeedAllowNone , 'Você deve estar em modo de ShowCheckbox para fixar esta data');
  SetResourceString(@sFailSetCalDateTime , 'Falha ao ajustar a data ou a hora do calendário');
  SetResourceString(@sFailSetCalMaxSelRange , 'Falha ao ajustar a escala máxima de seleção');
  SetResourceString(@sFailSetCalMinMaxRange , 'Falha ao ajustar a escala máxima do calendário');
  SetResourceString(@sCalRangeNeedsMultiSelect , 'A escala da data somente pode ser usada no modo multiseleção');
  SetResourceString(@sFailsetCalSelRange , 'Falha ao ajustar a escala selecionada do calendário');

  // COMCONST ==================================================================
  SetResourceString(@SCreateRegKeyError , 'Erro criando entrada de registro no sistema');
  SetResourceString(@SOleError , 'Erro OLE %.8x');
  SetResourceString(@SObjectFactoryMissing , 'Criador do objeto da classe %s desconhecida');
  SetResourceString(@STypeInfoMissing , 'Tipo de informação da classe %s desconhecida');
  SetResourceString(@SBadTypeInfo , 'Tipo de informação da classe %s incorreta');
  SetResourceString(@SDispIntfMissing , 'Interface do Dispatch da classe %s desconhecida');
  SetResourceString(@SNoMethod , 'Método "%s" não suportado pelo objeto de automação');
  SetResourceString(@SVarNotObject , 'Variante não pode fazer referência à um objeto de automação');
  SetResourceString(@STooManyParams , 'Método Dispatch não suporta mais do que 64 parâmetros');
  SetResourceString(@SDCOMNotInstalled , 'DCOM não instalado ou não encontrado');
  SetResourceString(@SDAXError , 'Erro DAX');
  SetResourceString(@SAutomationWarning , 'Alerta do servidor COM');
  SetResourceString(@SNoCloseActiveServer1 , 'Ainda há um objeto COM ativo na aplicação.' + 'Um ou mais clientes podem estar fazendo referência a este objeto, ' + 'Deve ser fechado manualmente ');
  SetResourceString(@SNoCloseActiveServer2 , 'Esta aplicação pode causar falhas nas ' + 'aplicação(ões) do cliente.'#13#10#13#10'Você quer fechá-la? ');
  SetResourceString(@sNoRunningObject , 'Não é possível recuperar um ponteiro para um objeto em execução registrado com OLE para %s/%s');
  SetResourceString(@sParameterCountExceeded , 'Contagem de parâmetro excedida');
  SetResourceString(@SBadPropValue , '''%s'' não é um valor de propriedade válido');
  SetResourceString(@SInvalidLicense , 'Informações de licença para %s são inválidas');
  SetResourceString(@SNotLicensed , 'Informações de licença para %s não encontradas. Você não pode utilizar esse controlador em modo de edição');
  SetResourceString(@SCannotActivate , 'Falha na ativação do controlador OLE');
  SetResourceString(@SNoWindowHandle , 'Não foi possível obter o identificador de janela de controle OLE');
end;

class procedure TTraducaoPT_BR.SetResourceString(
  xOldResourceString: PResStringRec; xValueChanged: PChar);
var
  POldProtect: DWORD;
begin
  VirtualProtect(xOldResourceString, SizeOf(xOldResourceString^),
                 PAGE_EXECUTE_READWRITE, @POldProtect);
   xOldResourceString^.Identifier := Integer(xValueChanged);
   VirtualProtect(xOldResourceString,SizeOf(xOldResourceString^),POldProtect,
                  @POldProtect);
end;

end.
